name: ctgan
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python==3.10
  - pip
  - pip:
    - torch==2.2
    - numpy
    - easydict
    - tqdm
    - pandas
    - wandb
    - wheel
    - matplotlib
